spring:
  application:
    name: woojudraw
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: ${REDIS_TIMEOUT:2s}
      password: ${REDIS_PASSWORD:}

  profiles:
    active: local

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    secret: "${JWT_SECRET:local-dev-secret-change-this-to-32+chars}"
    access-token-exp-min: 30
    refresh-token-exp-day: 14

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET:wud-upload}
      path:
        photo: ${AWS_S3_PHOTO_PATH:photos}
      presigned-url-exp-min: ${AWS_S3_PRESIGNED_URL_EXP_MIN:5}
    region:
      static: ${AWS_REGION:ap-northeast-2}
    stack:
      auto: false
    credentials:
      accessKey: ${AWS_ACCESS_KEY:}
      secretKey: ${AWS_SECRET_KEY:}

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
