spring:
  application:
    name: woojudraw

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/woojudraw
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug