spring:
  application:
    name: woojudraw
  data:
    redis:
      host: localhost
      port: 6379

  profiles:
    active: local

  datasource:
    url: jdbc:postgresql://localhost:5432/woojudraw
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: "CHANGE_ME_TO_LONG_RANDOM_BASE64"
    access-token-exp-min: 30
    refresh-token-exp-day: 14

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug