services:
  backend:
    platform: linux/amd64
    build:
      context: ../be/spring
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - ./.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    env_file:
      - ./.env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
    restart: always

  # frontend:
  #   build:
  #     context: ../fe
  #     dockerfile: Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   networks:
  #     - app-network
  #   restart: always

  ai:
    build:
      context: ../ai
      dockerfile: Dockerfile
    volumes:
      - ../ai:/app
    ports:
      - "8000:8000"
    env_file:
      - ../ai/.env
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - AI_RABBITMQ_EXCHANGE=wud.deep.ai.exchange
      - AI_RABBITMQ_REQUEST_QUEUE=wud.deep.ai.request.queue
      - AI_RABBITMQ_ROUTING_KEY=wud.deep.ai.request.routing-key
      - AI_RABBITMQ_RESULT_EXCHANGE=wud.deep.ai.exchange
      - AI_RABBITMQ_RESULT_ROUTING_KEY=wud.deep.ai.result.routing-key
    depends_on:
      - rabbitmq
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
